### ISSUE TITLE
Spurious warnings in StackTraceAnalyser

### ISSUE THREAD

**Issue by hwellmann** [serenity-bdd/serenity-core#113]
My logs contain lots of warnings of the following kind:

````
10:37:03.844 [main] WARN  n.t.c.reflection.StackTraceAnalyser - Failed to load class during Stack analysis: com.acme.Example$$Lambda$10/2123269713
````
It seems that StackTraceAnalyser cannot handle lambdas - if this cannot or need not be fixed, then at least it should stop complaining as lambdas are fairly normal when using Java 8.

**Comment by wakaleo** [comment]
Should be fixed in 1.1.6

**Comment by vividhsv** [comment]
Still getting lot of warning messages as below:
`[Test worker] WARN  n.t.c.r.StackTraceAnalyser - Failed to load class during Stack analysis: org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecuter`

Currently using version 1.1.24
