### ISSUE TITLE
Can't get details of Compromised tests from features view

### ISSUE THREAD

**Issue by ricardorlg** [serenity-bdd/serenity-core#1391]
With the latest version of serenity, if I have some scenarios that are compromised I can't go to the details of the tests from features tab, I only can see the details if I open the scenarios from test results tab in overall results.

**Comment by wakaleo** [comment]
Can you provide a sample project?

**Comment by wakaleo** [comment]
Also, what is the name of the scenario?

**Comment by ricardorlg** [comment]
@wakaleo There are also problems with broken and failed tests, for example, If a scenario outline has one broken test and one failed test the report is showing both tests as broken.

**Comment by wakaleo** [comment]
I'm going to need a sample project, I can't reproduce any of this behaviour at all.

**Comment by ricardorlg** [comment]
I will upload it in 1hour

**Comment by wakaleo** [comment]
I think this is fixed in 2.0.5

**Comment by wakaleo** [comment]
Could you check if this works in the latest version?

**Comment by ricardorlg** [comment]
I was trying this, in my project I still get the bug, but I was not able to replicate it in another project, is weird, let me investigate more about this and if I found the problem I will update the issue.

**Comment by ricardorlg** [comment]
@wakaleo finally I get the reason for my weird cases, If the name of a scenario contains a variable of examples tables, then serenity doesn't know how to report it in details. Also if a .feature is called test_reports and in the Feature file I define Feature: Test Reports serenity assume that there are two different features, that's the reason why I get that gray feature in the sample project, Also, another question in which case is possible that an example appears inside another example in the report?

I know this is weird bugs or cases but In one of my current projects (legacy) I'm getting these things.

**Comment by wakaleo** [comment]
The ghost feature issue is fixed in 2.0.8.

**Comment by ricardorlg** [comment]
@wakaleo I have a weird case wherein scenarios outline when I have broken and failed examples, the failed ones appears inside the last broken one in report 
![image](https://user-images.githubusercontent.com/4032481/47190277-1a576600-d306-11e8-9a47-d43c4b73368e.png)

**Comment by wakaleo** [comment]
I'm not seeing this in 2.0.8, could you update your sample project? 
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/55986/47193766-46103580-d372-11e8-91ab-fd359c1f19ec.png">

**Comment by ricardorlg** [comment]
@wakaleo that bug is happening in another project(private, company project), not in sample one, I will upload the serenity version to see if it fix it, In the sample one I can't reproduce the bug,  do u have any suggestions of where can I start to debug in order to get a reason or fix

**Comment by wakaleo** [comment]
See if updating helps. If not, it could be that the end of the step event is not being triggered correctly for some reason, so you could put some breakpoints in the StepEventBus to see how it is handling the errors.

**Comment by ricardorlg** [comment]
Great I will do that,in fact I have a doubt if a test fail in cucumber why the after method is not being executed

**Comment by wakaleo** [comment]
Closing for lack of activity.

**Comment by NSnietol** [comment]
@wakaleo,  could you explain to me how to set up an owned Exceptions ? since it seems serenity doesn't recognize it. I tried with Java Exceptions such as RunTimeException, SQLException and so and it worked.

`serenity.compromised.on=projectname.utils.MyTestException`

When I see the report I get this message `UnrecognisedException`.

![image](https://user-images.githubusercontent.com/12100190/111372967-5757ec00-8669-11eb-94dc-ff4de707a8b2.png)
