### ISSUE TITLE
Serenity 2.0.48 - It is not possible to pass list in serenity.properties for chrome_experimental_options

### ISSUE THREAD

**Issue by jacquecosta** [serenity-bdd/serenity-core#1781]
Inform a value of a list in serenity.properties, the property is not beign identified by serenity.

Example of property:
`chrome_experimental_options.excludeSwitches=enable-automation`

Error returned:
```
Caused by: net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate new WebDriver instance of type class org.openqa.selenium.chrome.ChromeDriver (invalid argument: cannot parse capability: goog:chromeOptions
from invalid argument: cannot parse excludeSwitches
from invalid argument: must be a list
```

At ChromeDriverCapabilites.java the code which treats the "chrome_experimental_options" calls for ChromePreferences.from(), but apparently this method doesn't recognizes list values.

```
public Map<String, Object> from(EnvironmentVariables environmentVariables) {
        List<String> propertiesWithPrefix =
            environmentVariables.getKeys()
                    .stream()
                    .filter( key -> key.startsWith(prefix))
                    .collect(Collectors.toList());

        Map<String, Object> preferences = new HashMap();

        for(String propertyKey : propertiesWithPrefix) {
            String preparedPropertyKey = getPreparedPropertyKey(propertyKey);
            String propertyValue = environmentVariables.getProperty(propertyKey);
            if (isNotEmpty(propertyValue)) {
                preferences.put(preparedPropertyKey, asObject(propertyValue));
            }
        }

        return preferences;
    }
```

Is there any way of inform "excludeSwitches=enable-automation" in serenity.properties?

My versions:
<serenity.version>2.0.48</serenity.version><serenity.cucumber.version>1.9.15</serenity.cucumber.version>

**Comment by wakaleo** [comment]
Do you know what the code would look like in plain Selenium to use this option?

**Comment by jacquecosta** [comment]
@wakaleo  

I've in touch with some examples, like: [Example](https://www.programcreek.com/java-api-examples/?class=org.openqa.selenium.chrome.ChromeOptions&method=setExperimentalOption).

I don't know if it is what exactly you've asked.

As a workaround I've created a custom driver:

```
ChromeOptions options = new ChromeOptions();
        options.setExperimentalOption("prefs", chromePrefs);
        options.setExperimentalOption("excludeSwitches", Arrays.asList("enable-automation"));
```

**Comment by jacquecosta** [comment]
I found this because in ChromeDriver version 76 they removed the ["--disable-inforbars"](https://support.google.com/chrome/a/answer/7679408?hl=en#76) and because of that some of my tests are breaking.

> --disable-infobars is no longer supported
> Chrome will no longer support the --disable-infobars flag, which was used to hide pop-up warnings from Chrome Browser. To support automated testing, kiosks, and automation, the CommandLineFlagSecurityWarningsEnabled policy was added to allow you to disable some security warnings.

And some people suggested to add those properties

```
options.setExperimentalOption("excludeSwitches", Arrays.asList("enable-automation"));
options.setExperimentalOption("useAutomationExtension", false);
```

Adding the CustomDriver with those information, the message of "chrome is being controlled by automated software" was gone, but, if serenity.properties support those properties that will be good.

**Comment by wakaleo** [comment]
This could be a bug, possibly fixed in 2.0.70. You would use:
```
chrome_experimental_options.excludeSwitches = "[enable-automation]"
chrome_experimental_options. useAutomationExtension = false
```

**Comment by jacquecosta** [comment]
Using 
`chrome_experimental_options.excludeSwitches = "[enable-automation]`

Still returning

```
Caused by: net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate new WebDriver instance of type class org.openqa.selenium.chrome.ChromeDriver (invalid argument: entry 0 of 'firstMatch' is invalid
from invalid argument: cannot parse capability: goog:chromeOptions
from invalid argument: cannot parse excludeSwitches
from invalid argument: must be a list
```

**Comment by wakaleo** [comment]
This will only work in version 2.0.70

**Comment by wakaleo** [comment]
Fixed in 2.0.70

**Comment by jacquecosta** [comment]
@wakaleo 

In version 2.0.71 the configuration haven't worked, in serenity.properties:

```
chrome_experimental_options.excludeSwitches="[enable-automation]"
chrome_experimental_options.useAutomationExtension=false
```

But the message of "chrome is being controlled by automated software" still appear. Using custom driver that works.

**Comment by wakaleo** [comment]
In serenity.properties, try:
```
chrome_experimental_options.excludeSwitches=[enable-automation]
chrome_experimental_options.useAutomationExtension=false
```

**Comment by jacquecosta** [comment]
With

```
chrome_experimental_options.excludeSwitches=[enable-automation]
chrome_experimental_options.useAutomationExtension=false
```

The result is:

`Caused by: net.thucydides.core.webdriver.DriverConfigurationError: Could not instantiate new WebDriver instance of type class org.openqa.selenium.chrome.ChromeDriver (invalid argument: entry 0 of 'firstMatch' is invalid
from invalid argument: cannot parse capability: goog:chromeOptions
from invalid argument: cannot parse excludeSwitches
from invalid argument: must be a list`

**Comment by wakaleo** [comment]
Can you raise a support ticket so we can look at this more closely?

**Comment by ankush2704** [comment]
@wakaleo to disable popup blocker I tried below two but none worked for me. On Serenity version 2.2.13
chrome_experimental_options.excludeSwitches=disable-popup-blocking
chrome_preferences.excludeSwitches="[disable-popup-blocking]"

Its opening the chrome but blocking popup.
