### ISSUE TITLE
 Aggregate not generate the report properly in Version 2.2.9 - (Your file was not found)

### ISSUE THREAD

**Issue by FranciscoSanQA** [serenity-bdd/serenity-core#2129]
Hi,
I´m working with a multi-module project following the instructions in this post:
https://johnfergusonsmart.com/configuring-different-output-directories-serenity-bdd-maven/
I am running in parallel  my tests with firefox and chrome.
Using  **version 2.2.9** and executing **mvn serenity:aggregate -Dserenity.outputDirectory=serenity-reports** at the end of the execution, the report is not generated properlty. 

**_Steps of the issue:_**

- run in parallel:
`mvn clean verify -Dcontext=chrome -Dinjected.tags="browser:chrome" -pl "acceptance" -am  -Dwebdriver.driver=chrome -P useTheForks`
`mvn clean verify -Dcontext=firefox -Dinjected.tags="browser:firefox" -pl "acceptance" -am  -Dwebdriver.driver=firefox -P useTheForks`

- Run aggregate:
`mvn serenity:aggregate -Dserenity.outputDirectory=serenity-reports`

**_Current results_**
- I can´t see the logo of the browser 
- When I click on the test, I can´t see the steps that I have defined in my code

![Screenshot 2020-06-14 at 18 49 20](https://user-images.githubusercontent.com/24686111/84599102-e1bbb700-ae6f-11ea-99c9-9b6e0b8a3bc4.png)

![Screenshot 2020-06-14 at 18 49 47](https://user-images.githubusercontent.com/24686111/84599104-e4b6a780-ae6f-11ea-84be-5d89df50dd51.png)

if I use version **2.2.8**,**2.2.7**, **2.2.6** ,**2.2.5** and **2.2.4** I get the same result. With the version **_2.2.2_** works correctly.

<img width="1433" alt="Screenshot 2020-06-14 at 18 40 42" src="https://user-images.githubusercontent.com/24686111/84599111-ebddb580-ae6f-11ea-8776-667f0567880d.png">

<img width="1438" alt="Screenshot 2020-06-14 at 18 40 57" src="https://user-images.githubusercontent.com/24686111/84599113-ef713c80-ae6f-11ea-9c1f-7b3c17727db1.png">

Do I have to take into account any other configuration in the latest version?

**Note**: I create a project to test this behavior https://github.com/FranciscoSanQA/myproject.git

**Comment by FranciscoSanQA** [comment]
hi @wakaleo , can you help me? 
thanks for your help

**Comment by FranciscoSanQA** [comment]
Hello, 
I update to  2.2.10 and  I´m  having  the same problem. 
Can anybody help me?
thank so  much
@wakaleo @derkoe @jeffjensen

**Comment by drash31** [comment]
I'm experiencing the very same problem in my tests. After some experimentation I created https://github.com/serenity-bdd/serenity-core/issues/2122, which was resolved, but unfortunately it didn't resolve the problem with missing reports reported here.
+1 for this issue.

**Comment by wakaleo** [comment]
@FranciscoSanQA Would you be able to propose a PR or raise a support ticket for this?

**Comment by wakaleo** [comment]
I can't reproduce this - maybe a Windows-specific issue?

**Comment by FranciscoSanQA** [comment]
Hi @wakaleo ,
thanks so much for the reply. 
I am working in my local with a macbook and I´m running  my tests too in  AWS3 with the same result.
I create a project demo in my space  https://github.com/FranciscoSanQA/myproject.git ( same result) to eva.
I create two branch : 
- v2.2.2 the last version where aggreate is working
- v2.2.9 Where I have the issue
Maybe you try  to reproduce the issue over there.
in the readme file I create the steps execution. Maybe it is a maven configuration? in the build?
Well the doubt is that in v2.2.2 it is working and in the other higher versions, no. 
Maybe a change between 2.2.2 and 2.2.3?
first of all thank you very much for the help
BR

**Comment by FranciscoSanQA** [comment]
Hi @wakaleo ,
I am going to try to open a support ticket for this. 
It is in this url https://johnfergusonsmart.com/serenity-bdd-mentoring/ to open the ticket? 
CONTACT SUPPORT link? 
I understand that it is to send an email.
BR

**Comment by FranciscoSanQA** [comment]
Good  afternoon @wakaleo ,
I send a email to reachme@johnfergusonsmart.com with this issue. 
This will be  the step to create a support ticket?
BR

**Comment by gizdolok** [comment]
I'm having this issue as well #2172

**Comment by wakaleo** [comment]
Fixed in 2.2.12

**Comment by FranciscoSanQA** [comment]
Hi @wakaleo ,
With the version 2.2.12 I still having the same result.
When I click on a scenario to see the step, I get your file was not found. 
Will be in the next release the fix?
thanks, BR

**Comment by wakaleo** [comment]
Sorry, this hasn't been fixed yet (I was confusing this with a different issue).

**Comment by FranciscoSanQA** [comment]
Hi John,
thanks for the reply and for reopening the ticket.
I'll be watching to know when it will be fixed.
BR

**Comment by wakaleo** [comment]
Not sure when it will get looked at, but if someone wants to have a go I'm happy to review.

**Comment by FranciscoSanQA** [comment]
Hi @wakaleo ,
I'm starting in this world of programming , if you give me some clues I can try to see if I can solve it(serenity-core).
Or else, if you tell me who can help me look at this error, I will mention it on the ticket.
If not, I am still waiting since ( I sent a email to reachme@johnfergusonsmart.com with this issue.)today in the project that I am starting I use this execution.
Thank so much for your help.
BR

**Comment by QATeam-ui** [comment]
Hi @wakaleo ,
I have update the version to 2.3.6 and it  is working correctly the aggregate action.
I think we can close this ticket.
thank you so much for your help 
BR

**Comment by tmouryc** [comment]
Hi @FranciscoSanQA. Was the issue resolved for you as well? I'm still having the problem with missing files after aggregation (meaning 2.2.2 is still the last functional version)

**Comment by sandeepraina1981** [comment]
@tmouryc I am also seeing the same issue. I tried the same project to test which @FranciscoSanQA attached for reference. 

2.2.2 is is last functional version for me too.

**Comment by FranciscoSanQA** [comment]
Hi @tmouryc @wakaleo , 
doing other tests I see that the issue still not resolved.  I did a mistake with the serenity version. 
We can re-open this issue?
some tips to how we can solve this in the serenity-core?

**Comment by wakaleo** [comment]
Have a look at the change history to see what might have caused the change, and propose a PR if you can find a fix.

**Comment by FranciscoSanQA** [comment]
thx @wakaleo for your quick response
@tmouryc @sandeepraina1981 ,
can you help us ?  with what is commented in the previous comment?
I'm going to try, but if you help us, it'll be great.
thx

**Comment by sandeepraina1981** [comment]
Thaanks @FranciscoSanQA for re-looking into this issue.

From my previous comment I meant that this issue still exists.

The last working version that I found was v2.2.2 since then this functionality is broken and not working properly.

When I try to pass a value to **context** parameter to enable multi-browser reporting then the report is gets created but the test-results page do not get displayed.

Removing the **context** parameter disables the multi-browser reporting but then for the report is generated properly for the last browser on which testing was done. 

So as per my understanding passing the value to the **context** parameter has some issue with the multi-browser reporting.

Please let me know if any additional information required from our end.

By the way I used the same project originally provided by you https://github.com/FranciscoSanQA/myproject.git for verification. And just updated the serenity core version along with its other dependent binary versions to the current latest one. I used cucumber 6 with the latest available binary version and could easily reproduce the original reported issue.

**Comment by FranciscoSanQA** [comment]
Hi @sandeepraina1981 , 
Thanks for the report.  I´m looking to the change history to see what might have caused the change.  
if you have time to take a look too, it would be nice to be able to identify where is the error  and do a PR.
Or if you know of someone who can help us.
thank  for your reply.

**Comment by ricardorlg-aval** [comment]
@wakaleo Assign this to me, please.

**Comment by ricardorlg-aval** [comment]
@wakaleo the problem is that since version 2.2.3, the method `getEnvironmentVariables()` in the TestOutcome class is called in more places, for example `getUnqualified()` or `getIssueKeys()`. The `getEnvironmentVariables()` violates the single responsibility, 

``` java 
 public EnvironmentVariables getEnvironmentVariables() {
        if (environmentVariables == null) {
            environmentVariables = Injectors.getInjector().getProvider(EnvironmentVariables.class).get();
            this.context = contextFrom(environmentVariables);
        }
        return environmentVariables;
    }
```
As you can see it returns the environmentVariables but also overrides the current context. so the easy solution is to remove that line, but I'm not sure why that line was added in first place, another solution could be to give priority to current context, so that method becomes:

```java
  public EnvironmentVariables getEnvironmentVariables() {
        if (environmentVariables == null) {
            environmentVariables = Injectors.getInjector().getProvider(EnvironmentVariables.class).get();
            if(this.context==null){ 
                this.context = contextFrom(environmentVariables);
            }
        }
        return environmentVariables;
    }
```
I've just tried that solution with the sample project provided in this issue, and it works, let me know if u like that solution so I can send the PR.

**Comment by wakaleo** [comment]
Yeah, I don't remember what that is about to be honest - I think your solution should be fine.

**Comment by ricardorlg-aval** [comment]
ok, I will send the PR, I think this also solves #2172 .
