### ISSUE TITLE
Serenity Report is not showing correct count of test cases.

### ISSUE THREAD

**Issue by cb-duppanapudisurya** [serenity-bdd/serenity-core#3060]
If there are failures in any of the test case which contains 7 lines, if 2 line is failing due to some error and the next 5 lines are taken as separate test cases. So every time I ran the test cases the total count is varying. 

And I need some clarity on scenarios which are having multiple examples is this type is considered as single test case or different test cases.

**Comment by wakaleo** [comment]
What version are you using? Can you provide some examples?

**Comment by cb-duppanapudisurya** [comment]
I am using serenity version : 3.6.12

**Comment by cb-duppanapudisurya** [comment]
<img width="1448" alt="Screenshot 2023-02-21 at 11 53 16 AM" src="https://user-images.githubusercontent.com/98867630/220263955-10d46eb8-b563-4b0e-819a-3a0de7dc7164.png">

In the above SS it is only 1 test case but it failed at enter PO number and all the other steps after that step is considered as separate test cases.

**Comment by wakaleo** [comment]
Can you provide some examples or a sample project?

**Comment by cb-duppanapudisurya** [comment]
Scenario Outline: Customer checkout
    Given chatlayer is the merchant
    And "James" is a new customer with the email address "xx"
    And the following billing address
    When he attempts to checkout the following items via "xx"
      | xx | xx |
    And makes the payment with
      | xx | xx |
    And provides the PO number "xx"
    And accepts the legal information
    And complete the order
    Then the merchant should have this new customer
    And the new customer should have a newly created <xx> subscription with all the cart items
    @P1
    Examples:
      | xx | xx |
      | xx | xx |
    @P2
    Examples:
      | xx | xx |
      | xx | xx |


SS: screenshot

**Comment by akshayrane1201** [comment]
I want to add to this thread that If anything fails in the _before hook_, then the corresponding scenarios' steps are added as separate tests to the count.

I had run 3 tests, in which _before hook_ code failed due to application issue for all 3 tests
You can see in the below report screenshot that _failed_ count is correctly shown but the _skipped_ count shows the count of all steps. Whereas another problem is that the _pass_ count belongs to the steps which were executed in the _after hook_ which were actually successful.

![image](https://user-images.githubusercontent.com/124863560/221605360-b078c2d4-4ce6-44a3-962c-c5f854ae4e8b.png)

**Comment by akshayrane308** [comment]
I want to add to this thread that If anything fails in the _before hook_, then the corresponding scenarios' steps are added as separate tests to the count.

I had run 3 tests, in which before hook code failed due to application issue for all 3 tests
You can see in the below report screenshot that _failed_ count is correctly shown but the _skipped_ count shows the count of all steps. Whereas another problem is that the _pass_ count belongs to the steps which were executed in the _after hook_ which were actually successful.

![image](https://user-images.githubusercontent.com/126495905/221607817-c5e910e1-92c5-4c62-ac4d-3c7adfa56047.png)

**Comment by wakaleo** [comment]
Should be fixed in 3.6.22

**Comment by cb-duppanapudisurya** [comment]
@wakaleo we are still facing the same issue even after changing the serenity latest version

**Comment by FaizKhan2119** [comment]
![image](https://github.com/serenity-bdd/serenity-core/assets/119660821/7a2d24e8-d672-45c5-a64a-d62c82347976)

![image](https://github.com/serenity-bdd/serenity-core/assets/119660821/128f8e2d-5e2a-4e10-b083-fc20636f8060)

I too am facing a similar issue.

**Comment by FaizKhan2119** [comment]
I too am facing a similar issue, I executed 8 scenarios, but it show 33 tests
![image](https://github.com/serenity-bdd/serenity-core/assets/119660821/2b0358ca-b6f0-4eb8-a63e-81743fa4e460)

![image](https://github.com/serenity-bdd/serenity-core/assets/119660821/234b976d-038b-408d-b917-cde97123ef65)

![image](https://github.com/serenity-bdd/serenity-core/assets/119660821/5debd0ff-5cc3-4e02-ae90-c02a25fba71f)

**Comment by wakaleo** [comment]
If you are using scenario outlines, each row is counted as a test case

**Comment by SrivaniChennupati** [comment]
@cb-duppanapudisurya  : I have also come across same behavior after upgrading to serenity 4 , did you do any workaround to resolve this ?
