### ISSUE TITLE
'Test outcome unavailable' in Serenity 3.6.12 + cucumber7 + junit5

### ISSUE THREAD

**Issue by p-nikolaichik** [serenity-bdd/serenity-core#3071]
`StepEventBus.getParallelEventBus().getBaseStepListener().getCurrentTestOutcome()` is empty in net.serenitybdd.core.webdriver.driverproviders.RemoteDriverProvider

![image](https://user-images.githubusercontent.com/29518579/222139728-d1c367ba-21bf-49db-ae07-4c1f406dd887.png)

@wakaleo could you confirm it was fixed or related to ticket https://github.com/serenity-bdd/serenity-core/issues/3037

**Comment by wakaleo** [comment]
This is a known issue related to the way parallel execution works - we are looking into seeing if a solution is possible.

**Comment by wakaleo** [comment]
Fixed in 3.6.22

**Comment by p-nikolaichik** [comment]
is reproduced for serenity.version - 3.6.22
net.thucydides.core.steps.StepEventBus#getBaseStepListener - CurrentListener is null
`<serenity.version>3.6.22</serenity.version>
        <junit.platform.version>1.9.2</junit.platform.version>
        <cucumber.junit.platform.engine.version>7.11.2</cucumber.junit.platform.engine.version>`
`<dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-cucumber</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-junit5</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-rest-assured</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-junit-platform-engine</artifactId>
            <version>${cucumber.junit.platform.engine.version}</version>
        </dependency>
        <dependency>
            <groupId>org.junit.platform</groupId>
            <artifactId>junit-platform-suite</artifactId>
            <version>${junit.platform.version}</version>
        </dependency>`

cucumber.execution.parallel.enabled=true
cucumber.execution.parallel.config.strategy=fixed
cucumber.execution.parallel.config.fixed.parallelism=60
cucumber.execution.parallel.config.fixed.max-pool-size=60
cucumber.filter.tags=not @skip and not @manual

![image](https://user-images.githubusercontent.com/29518579/230895725-bf0afc49-7326-448c-bff6-46c3e34428cb.png)

**Comment by p-nikolaichik** [comment]
oh, yes, thanks, I lost this line:  `cucumber.plugin=io.cucumber.core.plugin.SerenityReporterParallel`
nevertheless it seems like issue first issue is not fixed:
![image](https://user-images.githubusercontent.com/29518579/230905463-3a724bc9-2804-480f-bc86-755a5e96d8b6.png)

**Comment by wakaleo** [comment]
That's the nature of the parallel execution - the TestOutcome object isn't available until the end of the test.

**Comment by keshrey** [comment]
HI @p-nikolaichik , I am facing similar issue , Did you found any alternative to get scenario info before test starts in parallel execution?
