### ISSUE TITLE
Serenity BDD - For a failed scenario the report is showing skipped gherkin step as another scenario 

### ISSUE THREAD

**Issue by LetsCodeANewWorld** [serenity-bdd/serenity-core#3089]
Serenity-version - 3.6.12

I'm running a test suite using the {Serenity-version} and is working fine when all tests are passed. But in case of a failure, when i check the report it shows the failed scenario as well as the skipped step of that fail scenario under scenario column of report.
Hence, impacting the whole execution data and giving the incorrect number of test case.

Can anyone please suggest if there is any config property that i need to define to ignore the the skipped steps? I assumer it should not be the case and it should not displayed the skipped steps as tests/scenarios.
**{NOTE}** - It was working fine with the previous version and it is observed only after migrating to 3.6.7 or later

**Serenity.conf**
```
headless.mode=true

webdriver {
    driver = chrome
    autodownload = true
    timeouts {
      implicitlywait = 10000
      fluentwait = 5000
    }
    capabilities {
        "goog:chromeOptions" {
            args = ["--remote-allow-origins=*", "--no-sandbox", "ignore-certificate-errors", "--window-size=1260,860"
                       "incognito", "disable-infobars", "disable-gpu", "disable-default-apps", "disable-popup-blocking"]
        }
    }
}

serenity {
    tag.failures = true
    linked.tags = issue
    full.page.screenshot.strategy = true
    restart.browser.for.each = example
    use.unique.browser = false
    dry.run = false
    reports.show.step.details = true
    keep.unscaled.screenshots = true
    take.screenshots=FOR_FAILURES
}

```

**Screenshot**
[serenity-report-issue.pdf](https://github.com/serenity-bdd/serenity-core/files/11002114/serenity-report-issue.pdf)

**POM.XML**
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>******</groupId>
    <artifactId>>******</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name></name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <serenity.version>3.6.12</serenity.version>
        <browserstack.local.version>1.0.6</browserstack.local.version>
        <parallel.tests>8</parallel.tests>
        <per.core.thread.count>false</per.core.thread.count>
        <encoding>UTF-8</encoding>
        <tags></tags>

        
        <sonar.projectKey>****</sonar.projectKey>
        <sonar.projectName>${project.artifactId}</sonar.projectName>
        <sonar.language>java</sonar.language>
        <sonar.organization>>******</sonar.organization>
        <sonar.host.url>https://sonarcloud.io</sonar.host.url>
    </properties>

    <dependencies>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-junit</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-screenplay</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-screenplay-webdriver</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-ensure</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-cucumber</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.13.2</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>3.6.2</version>
            <scope>test</scope>
        </dependency>        
        <dependency>
            <groupId>com.browserstack</groupId>
            <artifactId>browserstack-local-java</artifactId>
            <version>${browserstack.local.version}</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.0.0-M5</version>
                <configuration>
                    <includes>
                        <include>**/features/**/*.java</include>
                        <include>**/cucumber/*.java</include>
                        <include>**/CucumberTestSuite.java</include>
                    </includes>
                    <threadCount>${parallel.tests}</threadCount>
                    <forkCount>${parallel.tests}</forkCount>
                    <parallel>methods</parallel>
                    <perCoreThreadCount>${per.core.thread.count}</perCoreThreadCount>
                    <useUnlimitedThreads>false</useUnlimitedThreads>
                    <testFailureIgnore>true</testFailureIgnore>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>3.0.0-M5</version>
                <configuration>
                    <skip>true</skip>
                    <includes>
                        <include>**/features/**/*.java</include>
                        <include>**/cucumber/*.java</include>
                        <include>**/CucumberTestSuite.java</include>
                    </includes>
                    <excludes>
                        <exclude>**/*WithFailures.java</exclude>
                    </excludes>
                    <parallel>methods</parallel>
                    <threadCount>${parallel.tests}</threadCount>
                    <forkCount>${parallel.tests}</forkCount>
                    <useUnlimitedThreads>true</useUnlimitedThreads>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.10.1</version>
                <configuration>
                    <release>11</release>
                </configuration>
            </plugin>
            <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>${serenity.version}</version>
                <configuration>
                    <tags>${tags}</tags>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>net.serenity-bdd</groupId>
                        <artifactId>serenity-core</artifactId>
                        <version>${serenity.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>org.apache.maven.shared</groupId>
                        <artifactId>maven-shared-utils</artifactId>
                        <version>3.3.4</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
    <repositories>
        <repository>
            <id>>******</id>
            <url>>******</url>
        </repository>
    </repositories>
</project>
`

**Comment by wakaleo** [comment]
Can you provide a sample project that reproduces this issue?

**Comment by ag-gggp** [comment]
@wakaleo 
Thanks for the quick response, attached is the sample cucumber project having 2 failed features (one failed and one error).

the command used  - `**mvn clean verify -Dcucumber.filter.tags="@Test2"**`

[serenity-cucumber-starter.zip](https://github.com/serenity-bdd/serenity-core/files/11010471/serenity-cucumber-starter.zip)

**Comment by wakaleo** [comment]
This should be fixed in version 3.6.15

**Comment by LetsCodeANewWorld** [comment]
@wakaleo Thanks for your quick response to the issue observed. 
I can see 3.6.15 version in mvn repository (screenshot), so assuming that the changes should be included in this. Please correct me, if this is not the release with the fix.
However , i've tested this 3.6.15 and i can still experience the same issue in this version too. Please suggest.
[serenity-3.6.15-mvn-repository.pdf](https://github.com/serenity-bdd/serenity-core/files/11012431/serenity-3.6.15-mvn-repository.pdf)

**Comment by wakaleo** [comment]
Can you provide a sample project that reproduces the issue? I reproduced a similar issue which was fixed in 3.6.15 so it may be a different issue.

**Comment by LetsCodeANewWorld** [comment]
> @wakaleo Thanks for the quick response, attached is the sample cucumber project having 2 failed features (one failed and one error).
> 
> the command used - `**mvn clean verify -Dcucumber.filter.tags="@Test2"**`
> 
> [serenity-cucumber-starter.zip](https://github.com/serenity-bdd/serenity-core/files/11010471/serenity-cucumber-starter.zip)

I 'm using the 👆  same project, the only change i made  is updated sereity-core version to 3.2.15. 
Command used is still same  - i.e. `**mvn clean verify -Dcucumber.filter.tags="@Test2"** `

**Comment by wakaleo** [comment]
That's odd - I tested the change with that project and it worked correctly with 3.6.15

**Comment by LetsCodeANewWorld** [comment]
Here is the report screenshot with highlighted 👇 

![serenityreport-error-3 6 15](https://user-images.githubusercontent.com/26610114/226215524-9699d0ca-2cbf-4f22-a50a-77af85960f77.jpg)

**Comment by wakaleo** [comment]
Fixed in 3.6.22

**Comment by ag-gggp** [comment]
@wakaleo 

I've tested the same with 3.6.22 and also with the latest 3.7.1, but i can still see the same behaviour. When a test is failed, the failed/skipped steps are coming under scenario column of report. Hence showing the incorrect number of test and % in pie chart. Can you please have a look.
[Serenity-cucumber-started.zip](https://github.com/serenity-bdd/serenity-core/files/11591227/Serenity-cucumber-started.zip)


<img width="1680" alt="2023-05-29_12-08-49" src="https://github.com/serenity-bdd/serenity-core/assets/86620078/ada4245e-e98c-4558-b4bb-e12b5618ed1a">
<img width="1680" alt="2023-05-29_12-09-09" src="https://github.com/serenity-bdd/serenity-core/assets/86620078/204a5fa9-72e8-4a47-9ad0-056e5d0b53f4">
