### ISSUE TITLE
With Serenity 1.1.36 more tests are flaky

### ISSUE THREAD

**Issue by hypery2k** [serenity-bdd/serenity-core#442]
I've updated my customer project to Serenity 1.1.36 and more tests are failing. If I go back to 1.1.34. Actually I cannot share the actual code, but I'm trying to create a sample project.

We're using a customized (extended version) of the CSV Runner in our project.

Did anybody else having same issues?

**Comment by wakaleo** [comment]
Could you try with the latest RC on Bintray (1.1.37-rc.2)?

___________________________________________________
John Smart | Wakaleo Consulting  |  +44 7398 832273
Making smart teams collaborate better

http://johnfergusonsmart.com  | reachme@johnfergusonsmart.com
<john.smart@wakaleo.com>___________________________________________________


On 9 June 2016 at 4:01:41 PM, Martin Reinhardt (notifications@github.com)
wrote:

I've updated my customer project to Serenity 1.1.36 and more tests are
failing. If I go back to 1.1.34. Actually I cannot share the actual code,
but I'm trying to create a sample project.

We're using a customized (extended version) of the CSV Runner in our
project.

Did anybody else having same issues?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/serenity-bdd/serenity-core/issues/442>, or mute the
thread
<https://github.com/notifications/unsubscribe/AADasrGzU76YdOd2KsPLOrfKaQ7ZLqN1ks5qKCq8gaJpZM4IyEeU>
.

**Comment by wakaleo** [comment]
Could you also give some examples of the errors you are getting? Are they related to timeouts?

**Comment by wakaleo** [comment]
Should be fixed in 1.1.37-rc.4

**Comment by hypery2k** [comment]
sorry for my late response. I was on vacation. The error still exits with 1.1.37-rc.5. I will try to create an anonym stripped down sample project for reproducing the issue

**Comment by hypery2k** [comment]
Getting the following errors:

```
Expected enabled element was not enabled
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'CTS0019199', ip: '10.129.19.95', os.name: 'Windows 7', os.arch: 'amd64', os.version: '6.1', java.version: '1.8.0_65'
Driver info: driver.version: unknown
```

**Comment by wakaleo** [comment]
The default behaviour for lists is now a bit more fine tuned and closer to native selenium behaviour - are you using lists in this test?
