### ISSUE TITLE
'Stack over Flow error' while running the longer tests

### ISSUE THREAD

**Issue by rakeshnambiar** [serenity-bdd/serenity-core#794]
I am getting this error while executing my tests with huge data sets.

This issue started appearing after I switch to the new serenity version - 1.3.1-rc.1 whereas it was working fine in the older version 1.1.37-rc.6

java.lang.StackOverflowError: null
	at net.thucydides.core.model.TestStep.renumberChildrenFrom(TestStep.java:84)
	at net.thucydides.core.model.TestStep.renumberFrom(TestStep.java:78)
        at net.thucydides.core.model.TestStep.renumberChildrenFrom(TestStep.java:85)
	at net.thucydides.core.model.TestStep.renumberFrom(TestStep.java:78)

**Comment by rakeshnambiar** [comment]
@wakaleo ... I saw this update later on and tried the latest version - 1.4.0. But still getting the same error.

 <serenity.version>1.4.0</serenity.version>
 <serenity.maven.version>1.4.0</serenity.maven.version>
 <serenity.cucumber.version>1.1.13</serenity.cucumber.version>

Am I doing any mistake? :(

**Comment by wakaleo** [comment]
Can you share a project that reproduces the issue?

**Comment by rakeshnambiar** [comment]
@wakaleo .. I have extracted the functionality which I had this issue in my framework.
Please note the repo - https://github.com/rakeshnambiar/SerenityTimeOut.git

**Comment by wakaleo** [comment]
I can't run this test sample as it is OS and environment-specific. Could you make a version that will run without needing Oracle or a custom driver on a Windows path?

**Comment by rakeshnambiar** [comment]
Done it. Pls, check now.
Now it won't use the custom driver and it uses the chrome browser by default.

**Comment by wakaleo** [comment]
This doesn't run on non-Windows environments, and seems to depend on an internal URL. Could you do a version that doesn't actually perform any testing, but still reproduces the issue?

**Comment by rakeshnambiar** [comment]
You are right. Unfortunately the URL not exposed to the public. But currently, I am facing this issue in this particular scenario. Let me wait and observe this issue for couple more days and in case it's failing for any public component, I will get back to you.

**Comment by rakeshnambiar** [comment]
Another update on this issue is the test now got stuck on the below process as per the log.

5593954 [pool-1-thread-1] INFO net.thucydides.core.reports.json.JSONTestOutcomeReporter - Generating JSON report
5595260 [pool-1-thread-2] INFO net.thucydides.core.reports.html.HtmlAcceptanceTestReporter - GENERATING HTML REPORT

It's been around 6-8 hours.

**Comment by wakaleo** [comment]
If you can get a thread dump it would help troubleshoot. If you are on Windows in may be other processes (e.g. Anti viruses) locking the report files.

**Comment by wakaleo** [comment]
If you can get a thread dump it would help troubleshoot. If you are on Windows in may be other processes (e.g. Anti viruses) locking the report files.

**Comment by rakeshnambiar** [comment]
Hello @wakaleo ... I have adjusted the code as you advised and now it should work in MAC OSx too.

During the investigation, I found the 'Scenario.write' causing the issue and if I commented this line and executes the tests the test went through successfully.
