### ISSUE TITLE
SerenityManagedException: org.openqa.selenium.support.ui.Wait.until(Lcom/google/common/base/Function;)Ljava/lang/Object;

### ISSUE THREAD

**Issue by oskarmora** [serenity-bdd/serenity-core#839]
Hi!

I recently updated to Selenium 3.4 and serenity 1.5.0-rc1.

However when I run some tests I am getting this exception: 
`
net.serenitybdd.core.exceptions.SerenityManagedException: org.openqa.selenium.support.ui.Wait.until(Lcom/google/common/base/Function;)Ljava/lang/Object;
	at net.thucydides.core.steps.ErrorConvertor.convertToAssertion(ErrorConvertor.java:22)
	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:342)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:134)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:61)
	at net.serenitybdd.screenplay.actions.EnterValueIntoTarget$$EnhancerByCGLIB$$5b6502b9.performAs(<generated>)
	at net.serenitybdd.screenplay.Actor.perform(Actor.java:98)
	at net.serenitybdd.screenplay.Actor.attemptsTo(Actor.java:82)
	at com.pki.spotfire.qa.at.common.tasks.LoginIntoTIBCO.performAs(LoginIntoTIBCO.java:35)
	at com.pki.spotfire.qa.at.common.tasks.LoginIntoTIBCO$$EnhancerByCGLIB$$72d9e7db.CGLIB$performAs$0(<generated>)
	at com.pki.spotfire.qa.at.common.tasks.LoginIntoTIBCO$$EnhancerByCGLIB$$72d9e7db$$FastClassByCGLIB$$d777d3b9.invoke(<generated>)
	at net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at net.thucydides.core.steps.StepInterceptor.invokeMethod(StepInterceptor.java:372)
	at net.thucydides.core.steps.StepInterceptor.executeTestStepMethod(StepInterceptor.java:357)
	at net.thucydides.core.steps.StepInterceptor.runTestStep(StepInterceptor.java:332)
	at net.thucydides.core.steps.StepInterceptor.testStepResult(StepInterceptor.java:134)
	at net.thucydides.core.steps.StepInterceptor.intercept(StepInterceptor.java:61)
	at com.pki.spotfire.qa.at.common.tasks.LoginIntoTIBCO$$EnhancerByCGLIB$$72d9e7db.performAs(<generated>)
	at net.serenitybdd.screenplay.Actor.perform(Actor.java:98)
	at net.serenitybdd.screenplay.Actor.attemptsTo(Actor.java:82)
	at com.pki.spotfire.qa.at.stepdefinitions.SpotfireStepDefinitions.login_into_tibco(SpotfireStepDefinitions.java:49)
	(reflection-invoke)
	at org.jbehave.core.steps.StepCreator$ParametrisedStep.perform(StepCreator.java:733)
	at org.jbehave.core.embedder.PerformableTree$FineSoFar.run(PerformableTree.java:346)
`

I have been googling this, and everybody points to the fact that it is necessary to update guava to at least version 21.0. I did it just by adding the dependency (attached the pom.xml [pom.zip](https://github.com/serenity-bdd/serenity-core/files/1145878/pom.zip)):

And also checked the dependency tree to not include older version of guava. 

However, the same error still appears. 

Could you guys help me out to identify what I did wrong ? (I am almost sure that I am missing something, but I am not able to understand the root of the problem)

Thanks a lot for your time!

Oscar

**Comment by wakaleo** [comment]
This should be fixed in 1.5.2.

**Comment by AndriiChorniak** [comment]
Hi, 

I`ve moved to 1.5.2 and this issue is still reproducible. Any updates with fluentWait issue?

**Comment by wakaleo** [comment]
This looks like a dependency conflict; I can't reproduce the issue. The latest version is 1.6.7.

**Comment by AndriiChorniak** [comment]
What dependency do you mean?

**Comment by wakaleo** [comment]
com/google/common/base/Function is from an old version of guava. In the latest versions of guava, which are used with Selenium 3.x and Serenity 1.5.x and higher, this is replaced by Java 8 functions. So you are trying to use an old version of guava.

**Comment by AndriiChorniak** [comment]
I have a question not related to this issue. I have moved to 1.6.7-rc.1. And I faced a new issue with initialize steps. 
I have variable.
@Steps
public SetupSteps test

And if method-step has annotation @Step, it does not work. If I remove this annotation, it warks as before with old version serenity. 
What can be the problem?

**Comment by wakaleo** [comment]
What do you mean when you say that it doesn't work?

**Comment by AndriiChorniak** [comment]
When I run test, this method(step) does not execute at all. I just write simple System.out.print("text") in this method and it does not print. When I try debug and go in this method to breakpoint, I can`t do it. When I delete annotation @Step, it works as expected

**Comment by wakaleo** [comment]
I would need a more complete example to understand. Could you post your test class and step class?

**Comment by AndriiChorniak** [comment]
sure

**Comment by AndriiChorniak** [comment]
public class AccessToGroupsWithRolesForInfoboxTests extends BaseTest {

    private Infobox infobox;

    @Steps
    private InfoboxEditSteps infobox_edit_steps;

    @Steps
    private InfoboxReadSteps infobox_read_steps;

    @Steps
    private SetupSteps test;

    @Before
    public void testSetup() {
        //reset implicit timeout
        test.reset_implicit_timeout();

        // get test handbook and test user from XML
        handbook = test.will_use_handbook_with_alias("default");
        user = test.will_be_run_as_user_with_alias("superuser");
        infobox = test.will_use_infobox_with_alias("for API tests");

        //create category by API
        restUtils.login(user);
        restUtils.createInfoBox(infobox, handbook);

        //open handbook as a specified user
        test.open_handbook_link_as_user(handbook, user);
    }

    @After
    public void restoreData() {
        restUtils.deleteItem(infobox, handbook);
    }

    @Test
    @Title("Infobox - User has denied access to group - test")
    @WithTags({
            @WithTag("Accesses"),
            @WithTag("Access - Infobox")
    })
    public void infobox_access_denied_group_test() {

        compublish.open_control_center();
        control_center.show_infoboxes();
        control_center.search(infobox);
        control_center.edit(infobox);

        infobox_edit_steps.open_access_tab();
        infobox_edit_steps.select_group_on_access_tab(Groups.GROUP_2_WITH_ROLE_2_ACCESSS_DENIED);
        infobox_edit_steps.complete_edit();

        infobox_edit_steps.should_error_be_displayed_about_access_to_group(Groups.GROUP_2_WITH_ROLE_2_ACCESSS_DENIED);
    }



//------------------step class-----------------

public class SetupSteps extends BaseSteps {
    public LoginPage loginPage;
    private BaseBlock baseBlock;

    @Steps
    LoginSteps loginSteps;
    @Steps
    HandbookSteps handbookSteps;
    
    
    @Step("Get test handbook by alias= \"{0}\"")
    public Handbook will_use_handbook_with_alias(String alias) {
        System.out.println("text");
        return xmlUtils.readData(HANDBOOKS_DATA_FILE, Handbooks.class).getHandbookByAlias(alias);
    }

**Comment by AndriiChorniak** [comment]
and the problem is with this line 
@Step("Get test handbook by alias= \"{0}\"")

**Comment by wakaleo** [comment]
Does the test pass or fail?

**Comment by AndriiChorniak** [comment]
it works on 1.2.2 version serenity.

**Comment by wakaleo** [comment]
Is it a web test?

**Comment by AndriiChorniak** [comment]
The problem is that this method does not execute at all. it is web.

**Comment by AndriiChorniak** [comment]
And if I delete annotation @Step("Get test handbook by alias= \"{0}\""), I can get into this method.

**Comment by wakaleo** [comment]
Then it is most likely a WebDriver version issue. If the test fails to start, it will be marked as "failed", and any subsequent @Step methods will be skipped/run in "dry-run" mode.

**Comment by AndriiChorniak** [comment]
when I try to open browser [driver.navigate().to(handbookLink)], I get 
java.lang.IllegalAccessError: tried to access method com.google.common.util.concurrent.SimpleTimeLimiter.<init>(Ljava/util/concurrent/ExecutorService;)V from class org.openqa.selenium.net.UrlChecker

**Comment by AndriiChorniak** [comment]
Thanks for your help!
